import { chromium } from '@playwright/test';
const out='C:/Users/DELL/AppData/Local/Temp/claude/C--Users-DELL-Desktop-VowFound/7c0b4c51-8ab0-44c3-9e12-4e5c6c92df27/scratchpad';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1440,height:900}});
await p.goto('http://127.0.0.1:3600/',{waitUntil:'networkidle'});
await p.getByRole('link',{name:'Begin your plan'}).first().click();
await p.waitForTimeout(1400);
await p.screenshot({path:`${out}/d-anchor.png`});
await p.getByRole('radio',{name:'Within 6 months'}).click();
await p.waitForTimeout(1500);
await p.screenshot({path:`${out}/d-selected.png`});
await b.close();
